### ISSUE TITLE
Link Trasero mejor girarlo para imprimirlo

### ISSUE THREAD

**Issue by ionhs** [robotaleh/PacifistaBot#1]
Hola los dibujos STL del Link Trasero para imprimir está complicado. ¿Podríais girarlos de manera que uno de los lados pueda estar apoyado sobre la cama? Sino o logiro a ojimetro (no muy recomendable), o lo imprimo verticalmente pero para eso hace falta ponerle un montón de soporte por lo que el tiempo de impresión se duplica y el material se malgasta. Os dejo una foto para que veais de lo que hablo. Gracias

![sin titulo](https://user-images.githubusercontent.com/11555122/49226412-c9e42580-f3e6-11e8-8bf2-a0c0e9252118.png)

**Comment by robotaleh** [comment]
Buenas!
Nosotros solemos usar Cura 3D y podemos girar las piezas angulos concretos estilo 90º y no tenemos problemas con ello. Sin embargo, es cierto que mejor dejar los STLs listos para imprimir en una posición ya óptima.

En cuanto tenga un momento, actualizo los STL.

Gracias!

**Comment by robotaleh** [comment]
He actualizado en a107da69a16159effd1ae7a9d6de380e6b56480f todos los STLs para colocarlos lo mejor posible para imprimir con la cantidad mínima de soportes.
